# Generated by Django 4.2.10 on 2024-02-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_image',
            new_name='image',
        ),
    ]
